export enum historyTypes {
  FETCH_HISTORY_REQUEST = "FETCH_HISTORY_REQUEST",
  FETCH_HISTORY_SUCCESS = "FETCH_HISTORY_SUCCESS",
  FETCH_HISTORY_FAILURE = "FETCH_HISTORY_FAILURE",
  POST_HISTORY_REQUEST = "POST_HISTORY_REQUEST",
  POST_HISTORY_SUCCESS = "POST_HISTORY_SUCCESS",
  POST_HISTORY_FAILURE = "POST_HISTORY_FAILURE",
}
