export enum usersTypes {
  FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST",
  FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE",
  POST_ONEUSER_REQUEST = "POST_ONEUSER_REQUEST",
  POST_ONEUSER_SUCCESS = "POST_ONEUSER_SUCCESS",
  POST_ONEUSER_FAILURE = "POST_ONEUSER_FAILURE",
}
