export enum vehicleTypes {
  FETCH_VEHICLES_REQUEST = "FETCH_VEHICLES_REQUEST",
  FETCH_VEHICLES_SUCCESS = "FETCH_VEHICLES_SUCCESS",
  FETCH_VEHICLES_FAILURE = "FETCH_VEHICLES_FAILURE",
  POSTONE_VEHICLE_REQUEST = "POSTONE_VEHICLE_REQUEST",
  POSTONE_VEHICLE_SUCCESS = "POSTONE_VEHICLE_SUCCESS",
  POSTONE_VEHICLE_FAILURE = "POSTONE_VEHICLE_FAILURE",
}
